#!/usr/bin/env bash

#prints "Best School" while integer values and if statement

i=1
while [ $i -le 10 ]
do
(( 1++ ))
if [ $i == 5 ]
then
echo "bad luck"

elif [ $i == 9 ]
then
echo "good luck"

else
echo "Best School"

fi
done
