#!/usr/bin/env bash

#prints "Best School" while integer is less than or equal to ten and prints "bad luck" when integer is equal to 4 and prints "good luck" when integer is equal to 8

i=1
while [ $i -le 10 ]
do
(( 1++ ))
if [ $i == 5 ]
then
echo "bad luck"

elif [ $i == 9 ]
then
echo "good luck"

else
echo "Best School"

fi
done
